# Generated by Django 5.1 on 2024-09-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tasks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=50)),
                ("is_completed", models.BooleanField(default=False)),
                ("created_at", models.DateField(auto_now_add=True)),
                ("update_at", models.DateField(auto_now=True)),
            ],
        ),
    ]
