# Generated by Django 5.1 on 2024-09-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
